In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.0.0-beta1'

In [4]:
tf.test.is_gpu_available()

True

In [16]:
import numpy as np
def softmax_temp(dist, temperature=1.0):
    dist = dist / temperature
    dist = np.exp(dist) / np.sum(np.exp(dist))
    return dist

In [21]:
s = np.array([0.9, 0.1, -1.2, -0.5, -2.0])

In [25]:
softmax_temp(s, temperature=2)

array([0.36344957, 0.24362753, 0.12718472, 0.18048371, 0.08525447])

In [26]:
softmax_temp(s, temperature=1)

array([0.53378724, 0.23984607, 0.06536568, 0.13163031, 0.02937069])

In [28]:
softmax_temp(s, temperature=0.5)

array([0.78080487, 0.15764179, 0.01170862, 0.04748079, 0.00236393])